# Generated by Django 5.2.4 on 2025-07-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_createticket_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createticket',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='media/upload/'),
        ),
    ]
